# Generated by Django 4.2.7 on 2025-07-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Raw content of the context entry')),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('calendar', 'Calendar'), ('manual', 'Manual Entry'), ('other', 'Other')], max_length=20)),
                ('sender', models.CharField(blank=True, help_text='Sender name or email', max_length=100)),
                ('recipients', models.JSONField(default=list, help_text='List of recipients')),
                ('timestamp', models.DateTimeField(help_text='When the context was created/received')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('processed_insights', models.JSONField(default=dict, help_text='AI-extracted insights from the content')),
                ('extracted_tasks', models.JSONField(default=list, help_text='Tasks identified from the context')),
                ('priority_indicators', models.JSONField(default=dict, help_text='Priority indicators extracted from context')),
                ('deadline_mentions', models.JSONField(default=list, help_text='Deadline mentions found in context')),
                ('key_entities', models.JSONField(default=list, help_text='Key entities (people, places, projects) mentioned')),
                ('sentiment_analysis', models.JSONField(default=dict, help_text='Sentiment analysis results')),
                ('categories', models.JSONField(default=list, help_text='AI-suggested categories for this context')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Relevance score for task management (0-100)')),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Context Entries',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_step', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='context.contextentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('task', 'Task Suggestion'), ('deadline', 'Deadline Mention'), ('priority', 'Priority Indicator'), ('contact', 'Contact Information'), ('meeting', 'Meeting Information'), ('project', 'Project Reference'), ('other', 'Other Insight')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0-100)')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the insight')),
                ('is_actionable', models.BooleanField(default=False, help_text='Whether this insight requires action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='context.contextentry')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['user', 'source_type'], name='context_con_user_id_2ecb08_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['processing_status'], name='context_con_process_a0bd66_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['timestamp'], name='context_con_timesta_262bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['relevance_score'], name='context_con_relevan_c6a1ad_idx'),
        ),
    ]
